### ISSUE TITLE
Broken link in Engage_Only_Integration_Guide.md

### ISSUE THREAD

**Issue by andressantiago** [janrain/jump.android#25]
[Engage_Only_Integration_Guide](https://github.com/janrain/jump.android/blob/master/Docs/Engage_Only_Integration_Guide.md)

The doc linked above contains a broken link for the `Gather Configuration Details` section.

The broken [link](http://developers.janrain.com/documentation/widgets/social-sign-in-widget/social-sign-in-widget-users-guide/configure-the-widget/provider-setup-guide/).

**Comment by pbjanrain** [comment]
Thanks, I think it is now here:

http://developers.janrain.com/overview/social-login/implementing-social-login/

**Comment by pbjanrain** [comment]
Resolved in 7.0.2 release.
