### ISSUE TITLE
Missing jcenter requirement from Engage_Only_Integration_Guide.md

### ISSUE THREAD

**Issue by andressantiago** [janrain/jump.android#28]
I get this error when attempting to build my app with Jump:

```
Error:Failed to resolve: net.openid:appauth:0.4.1
```

The fix for this was adding `jcenter()` to my app's build.gradle repositories.

It might be helpful to make a note of that in the Engage_Only_Integration_Guide.md.

**Comment by pbjanrain** [comment]
Thanks again Andres - I've made the jcenter() change for the 7.0.2 release.
