### ISSUE TITLE
Loading animation never dismissed when cancelling Google Sign In (Custom Tabs)

### ISSUE THREAD

**Issue by andressantiago** [janrain/jump.android#33]
Open google sign in via `mEngage.showAuthenticationDialog(this, "googleplus");` where `mEngage` is an instance of `JREngage`.

Tap on the `X` on the top left corner of the tab bar, the resulting screen shows a loading animation indefinitely.

Please let me know of any other information you might need.

Thanks.

**Comment by pbjanrain** [comment]
This should be resolved in the 7.0.4 release.  Please check the Upgrade_Guide and Release Notes for relevant changes.
