### ISSUE TITLE
7.0.4 crashing when opening google sign in.

### ISSUE THREAD

**Issue by andressantiago** [janrain/jump.android#36]
Opening google sign in via `mEngage.showAuthenticationDialog(this, "googleplus");` is causing a crash.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.ContextWrapper.getBaseContext()' on a null object reference
    at com.janrain.android.engage.JROpenIDAppAuth.signIn(JROpenIDAppAuth.java:240)
    at com.janrain.android.engage.JREngage.showOpenIDAppAuthFlowInternal(JREngage.java:928)
    at com.janrain.android.engage.JREngage.showAuthFlowInternal(JREngage.java:914)
    at com.janrain.android.engage.JREngage.showAuthenticationDialog(JREngage.java:728)
    at com.janrain.android.engage.JREngage.showAuthenticationDialog(JREngage.java:630)
```

**Comment by pbjanrain** [comment]
Are you actually doing an Engage only integration?  If you are using Registration/Capture you should not be using that method?

**Comment by andressantiago** [comment]
Yes Engage only.

**Comment by pbjanrain** [comment]
You must be the only one out there.  ;)  Investigating.

**Comment by pbjanrain** [comment]
It looks like I need to update the documentation for Engage Only.

You will need to do a little extra initialization before calling `mEngage.showAuthenticationDialog`

`AuthorizationService authorizationService = new AuthorizationService(MainActivity.this);
            mEngage.setAuthorizationService(authorizationService);
            mEngage.setAuthorizationActivity(MainActivity.this);
            mEngage.showAuthenticationDialog(MainActivity.this);`

Should work.

**Comment by pbjanrain** [comment]
https://github.com/janrain/jump.android/blob/master/Docs/Engage_Only_Integration_Guide.md
