### ISSUE TITLE
OpenIDAppAuthTokenActivity NullPointerException

### ISSUE THREAD

**Issue by andressantiago** [janrain/jump.android#39]
`OpenIDAppAuthTokenActivity.java` on line `154`

```
    private void receivedTokenResponse(
            @Nullable TokenResponse tokenResponse,
            @Nullable AuthorizationException authException) {
        LogUtils.logd(TAG, "Token request complete");
        LogUtils.logd(TAG, "Token: " + tokenResponse.accessToken);

        ...
```

`tokenResponse.accessToken` causing NPE sometimes.

**Comment by pbjanrain** [comment]
Could you please open a Janrain Support ticket through the Janrain Support portal (support.janrain.com) and provide more details, including:

- The Capture application you are testing against.
- The API Client you are testing with.
- The full log files including all the log data from the time the application is started to after any errors are thrown.
- The stack trace from when the error is thrown.

Please reference this Github issue in the ticket and ask them to escalate to engineering for analysis.

Thanks

**Comment by andressantiago** [comment]
Will do, I can close this then. Thanks for the details.
