### ISSUE TITLE
Correction in code : in the AndroidUtils.java class

### ISSUE THREAD

**Issue by varun2264** [janrain/jump.android#4]
Hello, 

This is Varun, and would like to bring to your notice that method defined below needs to be corrected and i have done it for you guys following which you can integrate it in your source code.

  public static void activitySetFinishOnTouchOutside(Activity activity, boolean finish) {
        try {
           //VARUN The method setFinishOnTouchOutside has been renamed to activitySetFinishOnTouchOutside by 
        	//janrain developers and they are trying to get it via reflection with a wrong method name
        	//**************************************
        	//Method m = activity.getClass().getMethod("activitySetFinishOnTouchOutside", boolean.class);
        	//**************************************
            Method m = activity.getClass().getMethod("setFinishOnTouchOutside", boolean.class);
            m.invoke(activity, finish);
        } catch (NoSuchMethodException e) {
            Log.e(TAG, "[activitySetFinishOnTouchOutside]", e);
        } catch (InvocationTargetException e) {
            Log.e(TAG, "[activitySetFinishOnTouchOutside]", e);
        } catch (IllegalAccessException e) {
            Log.e(TAG, "[activitySetFinishOnTouchOutside]", e);
        }
    }

Thanks

**Comment by pbjanrain** [comment]
Closed due to inactivity and duration passed.
