### ISSUE TITLE
Twitter sign in issue on back button press (webpage not available)

### ISSUE THREAD

**Issue by Write4Dinesh** [janrain/jump.android#41]
Hi,
we are working on an app in which janrain library is integrated for social sign in feature.
I have noticed an issue in twitter social sign in as stated below.
 when the user presses back button from the twitter sign in page and try to re-sign in , the the webpage not available error is shown all the time.

steps to reproduce:
1. click on twitter sign-in button (this button is our app specific)
2. the twitter sign-in page opens in  webView (with in JRWebViewFragment.java class)
3. press back button without signing in
4.the user is navigated back to previous screen.
5. repeat step 1 and 2 above.
6. we can see an error page with "webpage not available"

Note: To recover from this error, user requires to clear the data (not the cache) from app settings or re-install the app. (the issue only  re-appears if the user backs off from the sign in )

Devices: Samsung s5,s6,S7 edge,...,  OS = android, version : all
Janrain SDK verions : 7.0.1

pls help. let me know if you need any other info

Thanks,
Dinesh

**Comment by pbjanrain** [comment]
I believe this issue was resolved in SDK version 7.05:
https://github.com/janrain/jump.android/blob/master/RELEASE_NOTES
