### ISSUE TITLE
Yahoo sign in fails and results in a white screen

### ISSUE THREAD

**Issue by Write4Dinesh** [janrain/jump.android#42]
Hi, 

I have recently upgraded the Janrain SDK to V7.0.5 (the very latest one) and faced an issue in yahoo sign in.
When signing in thru Yahoo, it will just sit on a white screen and never sign in. the white screen ( with in the webview) never closes or redirects back to my app.  
Please help.
Note: i have seen this issue on old SDKs as well prior to upgrade.

Thanks
Dinesh

**Comment by Write4Dinesh** [comment]
Hello,
please  take a look at the above issue & share your insight about it.

**Comment by pbjanrain** [comment]
If you require urgent assistance please file a support ticket through support.janrain.com.

Thank you

**Comment by pbjanrain** [comment]
It appears that Yahoo is throwing a 500 error on their end.  Janrain is investigating what is going on.  Please check trust.janrain.com for official announcements or contact your Account Manager for additional information.
