### ISSUE TITLE
Maven artifact

### ISSUE THREAD

**Issue by narfman0** [janrain/jump.android#44]
Hi, happy to see this open source and available on github! A great next step would be to publish versioned artifacts somewhere like maven central. A 'Getting Started' section in README could include a single line to add to gradle instead of downloading the whole project and copy/pasting.

Are there any plans for this? Would you like any help doing so?

Thanks!

**Comment by pbjanrain** [comment]
Sorry I didn't see this sooner.  This will be done in our next iteration of Mobile Libraries which are being developed.  This code base is close to EOL and is mostly in maintenance.
