### ISSUE TITLE
EOF Exception

### ISSUE THREAD

**Issue by ppetarr** [janrain/jump.android#46]
I'm hitting an EOF exception at times, it's not consistent but it does happen. It happens when init is called on app start-up. I'm running different flavours of the same app, could this be a contributing factor?

**Comment by pbjanrain** [comment]
It sounds like some configuration data or saved state might not be getting read.  It's kind of hard to give any better guidance without the full debug logs.  If you are a Janrain customer you should be able to attach the full debug logs (from the launching of the app until you have acknowledged any error dialogs after the error) to a support ticket (http://support.janrain.com).  

Please attach the full logs and not just the error.  Sometimes the error is related to misconfiguration which is only reflected in the logs and not the error message.  

Thanks

**Comment by ppetarr** [comment]
I'm trying to replicate it, but it's not happening. I'll give it more testing later today so hopefully I can post the full logs then.

**Comment by pbjanrain** [comment]
Don't post any logs to Github - please use the support portal.  It's best to not expose any client ids to a public repo that is routinely crawled by search engines.
