### ISSUE TITLE
facebook login is failing with error "Missing or malformed token_url in query"

### ISSUE THREAD

**Issue by Write4Dinesh** [janrain/jump.android#47]
Hi devs,
our app was working great previously. but now it started throwing the below error when try to login with facebook. here is the error "Missing or malformed token_url in query".
I tried on the browser as well and saw the same error.
here is the url: 
https://<our-sub-domain>.rpxnow.com/facebook/start?device=android&extended=true&installation_id=<some previously working installation_id>.

Note: it happens on all android devices with all OS versions.

please help.
Thanks.
Dinesh

**Comment by pbjanrain** [comment]
Please file a support ticket for this issue at http://support.janrain.com.  The Github repo is not the correct place for support inquiries.  Thank you.
