### ISSUE TITLE
The Android Devices having a flap, crashes when ever the user is on the webView or any of the Janrain screens

### ISSUE THREAD

**Issue by varun2264** [janrain/jump.android#5]
The Android Devices having a flap, crashes when ever the user is on the webView or any of the Janrain screens
STR : 
You open the janrain provider list and u click any of the provider listed in your app
Lets say you click on the Google > the web view starts loading > then you open the flap of the device.
Its Then when we get the crash.

I was able to fix it by the following patch of code in oncreate().
I Hope this shall help you guys.

 @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LogUtils.logd(TAG, "[onCreate]: " + getFragmentId());

        JRSession session = JRSession.getInstance();

        /*VARUNif (session == null || savedInstanceState != null) {
             This flow control path is reached when there's process death and restart 
            Log.e(TAG, "bailing out after a process kill/restart. mSession: " + session);

            // prevent fragment recreation error -- the system needs the fragment's container to exist
            // even if the Activity is finishing right away
            setContentView(R.layout.jr_fragment_host_activity);
            super.finish();
            return;
        }*/

        if (session == null) {
            //This flow control path is reached when there's process death and restart 
           Log.e(TAG, "bailing out after a process kill/restart. mSession: " + session);

           // prevent fragment recreation error -- the system needs the fragment's container to exist
           // even if the Activity is finishing right away
           super.finish();
           return;
       }
        
        if (savedInstanceState == null) {
			switch (getFragmentId()) {
			case JR_PROVIDER_LIST:
				mUiFragment = new JRProviderListFragment();
				break;
			case JR_LANDING:
				mUiFragment = new JRLandingFragment();
				break;
			case JR_WEBVIEW:
				mUiFragment = new JRWebViewFragment();
				break;
			case JR_PUBLISH:
				mUiFragment = new JRPublishFragment();
				break;
			default:
				throw new IllegalFragmentIdException(getFragmentId());
			}
        } else {
        	setContentView(R.layout.jr_fragment_host_activity);
    		FragmentManager fm = getSupportFragmentManager();
    		mUiFragment = (JRUiFragment) fm.findFragmentByTag("tag");
    		return;
        }
        
        Bundle fragArgs = new Bundle();
        fragArgs.putInt(JRUiFragment.JR_FRAGMENT_FLOW_MODE, getFlowMode());
        fragArgs.putAll(getIntent().getExtras());
        mUiFragment.setArguments(fragArgs);

        mUiFragment.onFragmentHostActivityCreate(this, session);

        if (shouldBeDialog()) {
            AndroidUtils.activitySetFinishOnTouchOutside(this, false);
             if (shouldBePhoneSizedDialog()) {
                getTheme().applyStyle(R.style.jr_dialog_phone_sized, true);
            } else {
                getTheme().applyStyle(R.style.jr_dialog_71_percent, true);
            }

            if (!mUiFragment.shouldShowTitleWhenDialog()) {
                getTheme().applyStyle(R.style.jr_disable_title_and_action_bar_style, true);
            }
        } else if (getOperationMode() == JR_FULLSCREEN_NO_TITLE) {
            getWindow().requestFeature(Window.FEATURE_NO_TITLE);
            getTheme().applyStyle(R.style.jr_disable_title_and_action_bar_style, true);
        } else if (getOperationMode() == JR_FULLSCREEN) {
            // noop
        }

        setContentView(R.layout.jr_fragment_host_activity);

        View fragmentContainer = findViewById(R.id.jr_fragment_container);
        if (fragmentContainer instanceof CustomMeasuringFrameLayout) {
            // CMFL -> dialog mode on a tablet
            if (shouldBePhoneSizedDialog()) {
                // Do the actual setting of the target size to achieve phone sized dialog.
            	((CustomMeasuringFrameLayout) fragmentContainer).setTargetSizeDip(490, 670);
                if(mUiFragment instanceof JRProviderListFragment) {
                	JREngage.mProviderListDialog = true;
                 } else {
                 	JREngage.mProviderListDialog = false;
                 }
                getWindow().makeActive();
                WindowManager.LayoutParams lp = new WindowManager.LayoutParams();
                lp.copyFrom(getWindow().getAttributes());
                lp.height = AndroidUtils.scaleDipToPixels(670);
                lp.width = AndroidUtils.scaleDipToPixels(490);
                // After discussing it with Lilli we think it makes sense to let the height of the window
                // grow if the title is enabled
                //int targetHeight = mUiFragment.getCustomTitle() == null ? 480 : 560;
                //lp.height = AndroidUtils.scaleDipToPixels(targetHeight);
                getWindow().setAttributes(lp);
            }
        }

        getSupportFragmentManager()
                .beginTransaction()
                /*VARUN.add(R.id.jr_fragment_container, mUiFragment)*/
                .add(R.id.jr_fragment_container, mUiFragment, "tag")
                .setTransition(FragmentTransaction.TRANSIT_NONE)
                .commit();
    }

Thanks,
Varun

**Comment by pbjanrain** [comment]
Closed due to inactivity.
